[package]
name = "fileserver"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
once_cell = "1.17"
ratatui = "0.28.1"
crossterm = "0.28.1"
color-eyre = "0.6.3"
quote = "1.0"
proc-macro2 = "1.0"
